### ISSUE TITLE
Logging for the "check" step

### ISSUE THREAD

**Issue by marco-m** [cloudboss/ofcourse#12]
As you know, unfortunately Concourse doesn't show any logging for the check step (unless the check itself fails, in that case it shows it).

While developing my resource, I wanted logging support for check. I added it by sending a message to an HTTP IM service (in my case GChat, but it could easily be extended to any IM that supports HTTP POST).

Right now this HTTP logging is in the resource itself, but I wanted to bring it out in a dedicated library and make ofcourse use it, in a way that is transparent to the current ofcourse logging.

Would you be interested in such a feature? The current way to configure it is 

```
  source:
    log_url: ((my-secret-webhook))
```

if present, any ofcourse.log() calls would log also there, in addition to the resource stderr.

**Comment by rjosephwright** [comment]
I think it might be difficult to make this work in a generic way. What about making the Logger argument an interface and then you could extend the existing logger to work the way you want it to within your resource?

**Comment by marco-m** [comment]
Hello @rjosephwright,
Concourse 7.x finally prints, both to the web UI and to `fly check-resource`, the logging output of the `check` step of a resource.
As such, I am closing this ticket because nothing is needed to be done, it "just works"! :-)
